/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package christmas.tree

import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        Assertions.assertThat(classUnderTest.greeting).isNotNull()

    }
}
